# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Nemu-x.SlothClash
PackageVersion: 0.9.4
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
ProductCode: Nemu-xSloth Clash
AppsAndFeaturesEntries:
- DisplayName: Sloth Clash
  Publisher: Nemu-x
  ProductCode: Nemu-xSloth Clash
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Nemu-x/SlothClash/releases/download/v0.9.4/SlothClash-windows-amd64-installer.exe
  InstallerSha256: F5099CF583F51C720C26E1271C096CBC064734CD6D4F58A3D77EFCADE6185CF6
- Architecture: arm64
  InstallerUrl: https://github.com/Nemu-x/SlothClash/releases/download/v0.9.4/SlothClash-windows-arm64-installer.exe
  InstallerSha256: 4F4D70487894A27271FC33D03216A80C42852A7C9464E034C0CC5B11A6783392
ManifestType: installer
ManifestVersion: 1.10.0
